# Generated by Django 5.0.1 on 2024-01-14 04:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("proximity", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contact",
            options={"verbose_name": "Contact", "verbose_name_plural": "Contact"},
        ),
    ]
